### ISSUE TITLE
scjody is willing to take over the maintenance of this plugin

### ISSUE THREAD

**Issue by mlebkowski** [mlebkowski/dokku-acl#10]
Hey @scjody, meet @josegonzalez. Discuss ;)

**Comment by scjody** [comment]
@josegonzalez I'm interested in taking over as maintainer for dokku-acl. I'd like to update it for Dokku 0.8.x, and I'm willing to keep maintaining it after this. I work for a company that's going to be using Dokku a lot, so I can work on this during work hours and be a good maintainer. 😸

**Comment by josegonzalez** [comment]
Nailed it :)
