### ISSUE TITLE
Inconsistent return code for "acl:remove"

### ISSUE THREAD

**Issue by tarzzz** [mlebkowski/dokku-acl#26]
## Description of problem

`acl:remove` and `acl:remove-service` returns different return codes depending on the current state of the app.

### Steps to Reproduce

1. Initialize an app.
2. Add two users using `acl:add`
3. Remove them one-by-one.

#### Actual Results
Add two users to the app:
```
$# dokku acl:list app-1
$# dokku acl:add app-1 user1
$# dokku acl:add app-1 user2
```

Remove them one-by-one. When there is only one user linked to the app, the return code is `0`. When there are two users linked to the app, the return code is `1`.

```
$# dokku acl:remove app-1 user1
$# echo $?
1
$# dokku acl:remove app-1 user2
$# echo $?
0
```

#### Expected Results

Should return `0` return code in both cases:
```
$# dokku acl:remove app-1 user1
$# echo $?
0
$# dokku acl:remove app-1 user2
$# echo $?
0
```

@josegonzalez FYI  ⬆️ This probably because of [this](https://github.com/dokku-community/dokku-acl/blob/master/subcommands/remove#L27) line.

**Comment by josegonzalez** [comment]
Closed by #27.
