### ISSUE TITLE
Not able to set restrictions for commands used with dokku as mysql:connect

### ISSUE THREAD

**Issue by Fran4vila** [mlebkowski/dokku-acl#30]
## Description of problem
Now it is only possible to configure restrictions to commands related with git. However it could be good to have permissions over other plugins' commands as for example:

dokku **mysql:connect serviceName**

#### Expected Results
It could be good to set permissions for the users to alow or not execute this kind of command. Not only mysql, but also the commands "connect serviceName"

**Comment by josegonzalez** [comment]
Commands can be restricted [as documented in the readme](https://github.com/dokku-community/dokku-acl#command-restrictions), and are not restricted to git.

**Comment by Fran4vila** [comment]
Hello, 
I'm using the plugin and following the instructions I created the file dokku/.dokkurc/acl with this content:

export DOKKU_ACL_USER_COMMANDS="logs url urls ps:rebuild ps:restart ps:stop ps:start git-upload-pack git-upload-archive git-receive-pack git-hook"

but I still have permissions for executing: dokku mysql:connect database

According to the documentation, only if I include in the variable DOKKU_ACL_USER_COMMANDS the commands mysql:connect, this one should be accessible by other users, however this is not happening. Each user can execute any mysql command.

Could you help with this? The documentation is not clear enought and maybe this plugin is not limiting the access to other dokku plugins.

Thanks in advance!

**Comment by josegonzalez** [comment]
Are you logged in as the admin user? dokku-acl has an admin user, and maybe your ssh key maps to that user, so you're overriding that whitelist.

From the plugin's perspective, there isn't anything specific to being a core or non-core plugin in terms of checks for user-allowed commands.

**Comment by Fran4vila** [comment]
Hello,
I'm not logged as admin user, that's why is strange that I have permissions to mysql commands if this is not included in DOKKU_ACL_USER_COMMANDS. It seems that is not really restricting the usage.
