### ISSUE TITLE
Can't destroy app

### ISSUE THREAD

**Issue by MichaelSchroll** [mlebkowski/dokku-acl#5]
I can't seem to destroy any apps, no matter what tweaks I make to the acls -- I'm always denied:

> dokku@dokku:~/.dokkurc$ dokku apps:destroy 2222
>  !     WARNING: Potentially Destructive Action
>  !     This command will destroy 2222 (including all add-ons).
>  !     To proceed, type "2222"
> 
>  2222
> Destroying 2222 (including all add-ons)
> User  does not have permissions to modify this repository

**Comment by mlebkowski** [comment]
you’re destroying the app via command line, so I guess the `$NAME` variable is unset, effectively comparing an empty string to the ACL list. 

Could you try if this patch works?

``` patch
diff --git a/pre-build b/pre-build
index b65dfc6..1c1b15c 100755
--- a/pre-build
+++ b/pre-build
@@ -2,6 +2,7 @@
 set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

 APP="$1";
+NAME=${NAME:-$USER}
 ACL="$DOKKU_ROOT/$APP/acl"
 DOKKU_SUPER_USER="${DOKKU_SUPER_USER:-}"
```

**Comment by MichaelSchroll** [comment]
sorry for the extreme delay. Unfortunately no, that doesn't appear to have worked.
$ dokku ps:rebuild appname
User dokku does not have permissions to modify this repository
$ dokku acl:add appname dokku
$ dokku ps:rebuild appname

Or perhaps it did?
I had my account added to the dokku group; so I could run dokku commands...

**Comment by mlebkowski** [comment]
I’m not quite sure what’s happening. There is no error message any more, is there?

**Comment by MichaelSchroll** [comment]
Well; once I added 'dokku' then it works; so thats why I was saying maybe it did work... I just wasn't expecting 'dokku' to be the user I had to add; but instead one of the users listed in the acl settings...

**Comment by dmr** [comment]
I also cannot destroy an app: I see the following error message:

```
User  does not have permissions to modify this repository
```

**Comment by josegonzalez** [comment]
We should probably whitelist the dokku user.

**Comment by kjschulz** [comment]
👍 , I can't destroy apps either 😢

**Comment by dmr** [comment]
Yes, I think adding the dokku user solved the problem

**Comment by scjody** [comment]
It looks like at least one variant of this issue is caused by not handling commands run locally on the server (instead of through ssh) correctly. The easiest fix would be to modify the `pre-*` hooks to allow this case, but it's possible that some user depends on the existing behaviour for their security.

Therefore I believe the best fix is to add a configuration variable to enable local commands that check `pre-*` hooks, and fix the error message shown when a local command is denied.

**Comment by scjody** [comment]
The original behaviour (before any of my PRs) is weird and probably unintended. Here's what happens in various situations when a command that checks a `pre-*` hook is called from the command line:
1. No app ACL, no `DOKKU_SUPER_USER`: command succeeds
2. No app ACL, `DOKKU_SUPER_USER=testadmin`: `Only testadmin can modify a repository if the ACL is empty`
3. App ACL exists, no `DOKKU_SUPER_USER`: command succeeds
4. App ACL exists, `DOKKU_SUPER_USER=testadmin`: `User  does not have permissions to modify this repository`

(These behaviours are the same whether you run as user `dokku` or user `root`.)

I'm still concerned that someone might depend on behaviours 2 or 4, so I don't want to change the default behaviour of this plugin.

I think the best way forward is to add a `DOKKU_ACL_ALLOW_COMMAND_LINE` flag that defaults to false, and recommend in the documentation that users enable this flag. I'll also improve the error messages in cases 2 and 4.

If someone needs more advanced behaviour (like denying command line access, or restricting it to certain users), they can submit a PR...

@josegonzalez Any opinions on this?

**Comment by josegonzalez** [comment]
Sounds fine with me, though the dokku user really should be whitelisted be default, as it's more likely someone will expect that to work than not.

**Comment by scjody** [comment]
@josegonzalez Unfortunately there doesn't seem to be a way to tell the dokku user apart from a user who's using dokku via sudoers as described in: http://dokku.viewdocs.io/dokku~v0.8.2/deployment/user-management/#granting-other-unix-user-accounts-dokku-access

I don't want to open this up by default, which is why I propose preserving the existing behaviour (but giving a better error message so folks can figure out what's going on).

**Comment by scjody** [comment]
Now that I'm further into my fix, I'm even more convinced that this is the right thing to do. The weird behaviour only occurs if `DOKKU_SUPER_USER` is set, and in that case the user will have read the documentation and will know to set `DOKKU_ACL_ALLOW_COMMAND_LINE` as well.
