### ISSUE TITLE
After the access was restricted, all apps were stopped :(

### ISSUE THREAD

**Issue by dmr** [mlebkowski/dokku-acl#6]
I defined a superuser that did not exist, and after i pushed the push was rejected.

All running dokku apps were stopped and I had to restart manually.
Did that happen to anybody else?

**Comment by mlebkowski** [comment]
@dmr, I am no longer involved in dokku so I transfered the plugin to the dokku community. I hope it will find a new maintainer there and your problem gets resolved

**Comment by josegonzalez** [comment]
@dmr What are the exact reproduction steps for this?

**Comment by dmr** [comment]
I'm still not sure how to reproduce. Let's close this until it happens again
