### ISSUE TITLE
Transfer repo to dokku-community

### ISSUE THREAD

**Issue by josegonzalez** [mlebkowski/dokku-acl#9]
Hi! I saw your comment on chat, and was hoping you'd transfer the repository to the `dokku-community` organization. It will serve as a hub for plugins that may no longer get the attention they need from their maintainers, and hopefully allow us to provide better testing of said plugins going forward.

**Comment by mlebkowski** [comment]
Have a great life at your new home, `dokku-acl`! ;)

**Comment by josegonzalez** [comment]
So long, and thanks for all the fish!
